name: dain
description: A dynamic dependency injection framework for Dart developers.
version: 0.0.4
author: KazaKago <weathercock-perch@yahoo.co.jp>
homepage: https://github.com/KazaKago/Dain

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.9.3
