name: dain
description: A dynamic dependency injection framework for Dart developers.
version: 0.1.0
homepage: https://github.com/KazaKago/Dain

environment:
  sdk: ">=2.12.0 <3.0.0"

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic_mono: ^1.11.0+2
  test: ^1.16.5
